### ISSUE TITLE
Node version v8.11.1 not support "**" operator

### ISSUE THREAD

**Issue by llcat** [kevincharm/moov-faststart#2]
may be it's my node version not support `BigInt` ?
I see the document, your tool works require node version>v8.6.7

console log:
![1](https://user-images.githubusercontent.com/17900822/51067413-05604980-164d-11e9-9d86-9a44bd327c4d.png)

my node version
![2](https://user-images.githubusercontent.com/17900822/51067415-085b3a00-164d-11e9-840b-45b37928bd4f.png)

**Comment by kevincharm** [comment]
Actually the README says you need Node >10.4 for BigInt support. That'll be your problem :)

**Comment by llcat** [comment]
> support

ok, thanks!
